@ECHO OFF

SET HB_BUILD_DEBUG=no
SET HB_BUILD_DLL=yes
SET HB_BUILD_IMPLIB=no
SET HB_BUILD_MODE=cpp
SET HB_BUILD_OPTIM=yes
SET HB_BUILD_PKG=yes

SET HB_COMPILER=msvc
set HB_PATH=C:\hb_msvc
SET HB_QT_MAJOR_VER=5
SET QT_PATH=C:\Qt\Qt5.6.0\5.6\msvc2015
SET HB_WITH_QT=%QT_PATH%\include

SET PATH=C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;%HB_PATH%\bin;%QT_PATH%\bin;C:\UTIL

SET LIB=%HB_PATH%\lib
SET Include=%HB_PATH%\Include

IF "%VS140COMNTOOLS%" == "" GOTO Build_V120
CALL "%VS140COMNTOOLS%vsvars32.bat"
GOTO end

:Build_V120
IF "%VS120COMNTOOLS%" == "" GOTO Build_V110
CALL "%VS120COMNTOOLS%vsvars32.bat" x86
GOTO end

:Build_V110
IF "%VS110COMNTOOLS%" == "" GOTO Build_V100
CALL "%VS110COMNTOOLS%vsvars32.bat" x86
GOTO end

:Build_V100
IF "%VS100COMNTOOLS%" == "" GOTO Build_V90
CALL "%VS100COMNTOOLS%vsvars32.bat" x86
GOTO end

:Build_V90
IF "%VS90COMNTOOLS%" == "" GOTO Build_Error
CALL "%VS90COMNTOOLS%vsvars32.bat" x86
GOTO end

:Build_Error
@ECHO *
@ECHO *
@ECHO * FATAL ERROR - MSVC NOT DETECTED
@ECHO *
@ECHO *
GOTO end

:end
HARBOUR -build
%ComSpec%
