@ECHO OFF

set HB_PATH=C:\hb_msvc
SET HB_BUILD_DEBUG=no
SET HB_BUILD_DLL=yes
SET HB_BUILD_IMPLIB=no
SET HB_BUILD_MODE=cpp
SET HB_BUILD_OPTIM=yes
SET HB_BUILD_PKG=yes
SET HB_QT_MAJOR_VER=5
SET QT_PATH=C:\Qt\Qt5.6.0\5.6\msvc2015
SET HB_WITH_QT=%QT_PATH%\include

SET LIB=%HB_PATH%\lib
SET Include=%HB_PATH%\Include

IF "%VS140COMNTOOLS%" == "" GOTO Build_V120
SET HB_COMPILER=msvc
SET PATH=C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;%HB_PATH%\bin;%QT_PATH%\bin;C:\UTIL
CALL "%VS140COMNTOOLS%vsvars32.bat"
GOTO end

:Build_V120
IF "%VS120COMNTOOLS%" == "" GOTO Build_V110
SET HB_COMPILER=msvc
SET PATH=C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;%HB_PATH%\bin;%QT_PATH%\bin;C:\UTIL
CALL "%VS120COMNTOOLS%vsvars32.bat" x86
GOTO end

:Build_V110
IF "%VS110COMNTOOLS%" == "" GOTO Build_V100
SET HB_COMPILER=msvc
SET PATH=C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;%HB_PATH%\bin;%QT_PATH%\bin;C:\UTIL
CALL "%VS110COMNTOOLS%vsvars32.bat" x86
GOTO end

:Build_V100
IF "%VS100COMNTOOLS%" == "" GOTO Build_V90
SET HB_COMPILER=msvc
SET PATH=C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;%HB_PATH%\bin;%QT_PATH%\bin;C:\UTIL
CALL "%VS100COMNTOOLS%vsvars32.bat" x86
GOTO end

:Build_V90
IF "%VS90COMNTOOLS%" == "" GOTO Build_MingW
SET HB_COMPILER=msvc
SET PATH=C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\hb_MingW\bin;%QT_PATH%\bin;C:\UTIL
CALL "%VS90COMNTOOLS%vsvars32.bat" x86
GOTO end

:Build_MingW
SET HB_COMPILER=mingw
SET PATH=C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;%HB_PATH%\bin;%HB_PATH%\mingw\bin;%QT_PATH%\bin;C:\UTIL
GOTO end

:end
HARBOUR -build
%ComSpec%
